export const CHANGE_SEASON_PAGE_SIZE = 'CHANGE_SEASON_PAGE_SIZE'
export const LOAD_SEASON_LIST = 'LOAD_SEASON_LIST'
export const SET_LOADING_SEASON = 'SET_LOADING_SEASON'
export const SET_ERROR_SEASON = 'SET_ERROR_SEASON'