export const LOAD_RACE_DETAILS = 'LOAD_RACE_DETAILS'
export const SET_LOADING_RACE_DETAILS = 'SET_LOADING_RACE_DETAILS'
export const SET_ERROR_RACE_DETAILS = 'SET_ERROR_RACE_DETAILS'
export const SET_FILTERED_LIST = 'SET_FILTERED_LIST'